//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Komalli.DataBaseManagement.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int Sale { get; set; }
        public int Product { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Total { get; set; }
    
        public virtual Product Product1 { get; set; }
        public virtual Sale Sale1 { get; set; }
    }
}
