//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Komalli.DataBaseManagement.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovementType()
        {
            this.ExtraordinaryMovements = new HashSet<ExtraordinaryMovements>();
        }
    
        public int MovementTypeId { get; set; }
        public string MovementType1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtraordinaryMovements> ExtraordinaryMovements { get; set; }
    }
}
