//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Komalli.DataBaseManagement.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Bill = new HashSet<Bill>();
            this.SpoilageDetail = new HashSet<SpoilageDetail>();
        }
    
        public int ProductId { get; set; }
        public decimal Price { get; set; }
        public int AvailableQuantity { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> SellingDate { get; set; }
        public bool FromKitchen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bill { get; set; }
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpoilageDetail> SpoilageDetail { get; set; }
    }
}
